Array Attribute

In [2]:
import numpy as np

In [82]:
one_d_array = np.array([1,2,3,4,5])  # 1D array
print(one_d_array) # array print
type(one_d_array) #type of array

[1 2 3 4 5]


numpy.ndarray

In [83]:
one_d_array.shape #shape of array 

(5,)

In [84]:
one_d_array.ndim #dimention of array 

1

In [85]:
two_d_array = np.array([[1,2,3],[4,5,6]])
print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [86]:
three_d_array = np.array([[1.0, 2, 3, 4], [5, 6, 7.5, 8], [0, 9.8, 5, 4]])
print(three_d_array)

[[1.  2.  3.  4. ]
 [5.  6.  7.5 8. ]
 [0.  9.8 5.  4. ]]


In [87]:
one_d_array.dtype, two_d_array.dtype, three_d_array.dtype #type of array 

(dtype('int32'), dtype('int32'), dtype('float64'))

In [88]:
one_d_array.size, two_d_array.size, three_d_array.size #size of arrays

(5, 6, 12)

In [89]:
one_d_array.nbytes, two_d_array.nbytes, three_d_array.nbytes #how many bytes consume

(20, 24, 96)