Array Creation


In [76]:
import numpy as np

In [77]:
# ------------------------------------------------------------------------------------
# The numpy.zeros() function returns a new array of given shape and type, with zeros. 
# Syntax:
# numpy.zeros(shape, dtype = None, order = 'C')
# ------------------------------------------------------------------------------------
# Parameters :
# shape : integer or sequence of integers
# order  : C_contiguous or F_contiguous

#          C-contiguous order in memory(last index varies the fastest)
#          C order means that operating row-rise on the array will be slightly quicker
#          FORTRAN-contiguous order in memory (first index varies the fastest).
#          F order means that column-wise operations will be faster. 
# dtype : [optional, float(byDeafult)] Data type of returned array.
# ------------------------------------------------------------------------------------
# Returns : 
# ndarray of zeros having given shape, order and datatype.
# ------------------------------------------------------------------------------------
# Code:
zeros_arr = np.zeros((2,2), dtype="int") # all element of array will be 0, dimention 2x2 and data type int 
print(zeros_arr)

[[0 0]
 [0 0]]


In [78]:
# ------------------------------------------------------------------------------------
# The numpy.ones() function returns a new array of given shape and type, with ones.
 # ------------------------------------------------------------------------------------
# Syntax: numpy.ones(shape, dtype = None, order = 'C') 
# ------------------------------------------------------------------------------------
# Parameters : 
# shape : integer or sequence of integers
# order  : C_contiguous or F_contiguous
#          C-contiguous order in memory(last index varies the fastest)
#          C order means that operating row-rise on the array will be slightly quicker
#          FORTRAN-contiguous order in memory (first index varies the fastest).
#          F order means that column-wise operations will be faster. 
# dtype : [optional, float(byDefault)] Data type of returned array.
# ------------------------------------------------------------------------------------
# Returns : 
# ndarray of ones having given shape, order and datatype.
# ------------------------------------------------------------------------------------
# Code :
ones_arr = np.ones((3,3), dtype="float") # all element of array will be 1, dimention 3x3 and data type float 
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [79]:
# ------------------------------------------------------------------------------------------
# numpy.full(shape, fill_value, dtype = None, order = ‘C’) : 
# Return a new array with the same shape and type as a given array filled with a fill_value.
# ------------------------------------------------------------------------------------------
# Parameters :
# shape      : Number of rows
# order      : C_contiguous or F_contiguous
# dtype      : [optional, float(by Default)] Data type of returned array.  
# fill_value : [bool, optional] Value to fill in the array.
# ------------------------------------------------------------------------------------------
# Returns :
# ndarray
# ------------------------------------------------------------------------------------------
# Code :
full_arr = np.full((4,3), 9, dtype="int") # all element of array will be 9 (as given), dimention 3x3 and data type int 
print(full_arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]


In [80]:
# ---------------------------------------------------------------------------------------------------------------
# numpy.identity(n, dtype = None) : Return a identity matrix i.e. a square matrix with ones on the main diagonal.
# ---------------------------------------------------------------------------------------------------------------
# Parameters :
# n : [int] Dimension n x n of output array  
# dtype : [optional, float(by Default)] Data type of returned array.
# ---------------------------------------------------------------------------------------------------------------
# Returns : 
# identity array of dimension n x n,  with its main diagonal set to one, and all other elements 0.
# ---------------------------------------------------------------------------------------------------------------
# Code :
identity_arr = np.identity(5, dtype="int") # identity matrix is a squre matrix, which row is equal to column. So, dimention will be 5x5
print(identity_arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [81]:
# ---------------------------------------------------------------------------------------------------------------------
# numpy.eye(R, C = None, k = 0, dtype = type <‘float’>) : 
# The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere. 
# The diagonal can be main, upper, or lower depending on the optional parameter k. 
# A positive k is for the upper diagonal, a negative k is for the lower, and a  0 k (default) is for the main diagonal.
# ---------------------------------------------------------------------------------------------------------------------
# R : Number of rows
# C : [optional] Number of columns; By default M = N
# k : [int, optional, 0 by default]
# Diagonal we require; k>0 means diagonal above main diagonal or vice versa.
# dtype : [optional, float(by Default)] Data type of returned array. 
# ---------------------------------------------------------------------------------------------------------------------
# Code :
eye_arr = np.eye(5, 5, k = 0, dtype="int") # matrix with R=4 C=5 and 1 on diagonal
print(eye_arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [82]:
# ----------------------------------------------------------------------------------------
# The arange([start,] stop[, step,][, dtype]) : 
# Returns an array with evenly spaced elements as per the interval. 
# The interval mentioned is half-opened i.e. [Start, Stop) 
# ----------------------------------------------------------------------------------------
# start : [optional] start of interval range. By default start = 0
# stop  : end of interval range
# step  : [optional] step size of interval. By default step size = 1,  
# For any output out, this is the distance between two adjacent values, out[i+1] - out[i].
# ----------------------------------------------------------------------------------------
# dtype : type of output array
# ----------------------------------------------------------------------------------------
# Code :
arange_arr = np.arange(1, 10)
arange_arr2 = np.arange(1, 50, 5)
print(arange_arr)
print(arange_arr2)

[1 2 3 4 5 6 7 8 9]
[ 1  6 11 16 21 26 31 36 41 46]


In [83]:
# The numpy.linspace() function returns number spaces evenly w.r.t interval. 
# Similar to numpy.arange() function but instead of step it uses sample number.
# -----------------------------------------------------------------------------
# Syntax : 
# numpy.linspace(start,
#                stop,
#                num = 50,
#                endpoint = True,
#                retstep = False,
#                dtype = None)
# -----------------------------------------------------------------------------
# Parameters : 
# -> start  : [optional] start of interval range. By default start = 0
# -> stop   : end of interval range
# -> restep : If True, return (samples, step). By default restep = False
# -> num    : [int, optional] No. of samples to generate
# -> dtype  : type of output array
# -----------------------------------------------------------------------------
# Return : 
# -> ndarray
# -> step : [float, optional], if restep = True
# -----------------------------------------------------------------------------
# Code :
linspace_arr = np.linspace(1, 10, 20)
print(f"Array = {linspace_arr} \n Array Size = {linspace_arr.size}")

Array = [ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ] 
 Array Size = 20


In [84]:
# ---------------------------------------------------------------------
# numpy.empty(shape, dtype = float, order = ‘C’) : 
# Return a new array of given shape and type, with random values.
# ---------------------------------------------------------------------
# Parameters :
# -> shape : Number of rows
# -> order : C_contiguous or F_contiguous
# -> dtype : [optional, float(by Default)] Data type of returned array.
# ---------------------------------------------------------------------
# Code :
empty_one_d_arr = np.empty(2, dtype="int")
empty_two_d_arr = np.empty((3,3), dtype="int")
print(f"ONE D EMPTY ARRAY = {empty_one_d_arr}\nTWO D EMPTY ARRAY = {empty_two_d_arr}")

ONE D EMPTY ARRAY = [         0 1076101120]
TWO D EMPTY ARRAY = [[1 2 3]
 [4 5 6]
 [7 8 9]]
