Array Slicing

In [1]:
import numpy as np

In [6]:
one_d_array = np.array([1,2,3,4,5])  # 1D array
print(one_d_array) # array print
print(f"Afetr slice first 3 item : {one_d_array[:3]}") # array print
print(f"Afetr slice last 3 item : {one_d_array[2:]}") # array print


[1 2 3 4 5]
Afetr slice first 3 item : [1 2 3]
Afetr slice last 3 item : [3 4 5]


In [19]:
two_d_array = np.random.randint(1, 10, size=(3,3))  # 2D array
print(two_d_array) # array print
print(f"After slice 4 right bottom item : \n {two_d_array[1:, 1:]}") # array print

[[3 7 2]
 [3 7 7]
 [3 1 5]]
After slice 4 right bottom item : 
 [[7 7]
 [1 5]]
