Array Ravel

In [2]:
import numpy as np

In [8]:
# ----------------------------------------------------------------------------------------------------------------------------------------
# The numpy.ravel() functions returns contiguous flattened array(1D array with all the input-array elements and with the same type as it). 
# A copy is made only if needed.
# ----------------------------------------------------------------------------------------------------------------------------------------

# Syntax : 
# numpy.ravel(array, order = 'C')
# ----------------------------------------------------------------------------------------------------------------------------------------
# Parameters :  
# array : [array_like]Input array. 
# order : [C-contiguous, F-contiguous, A-contiguous; optional]         
#          C-contiguous order in memory(last index varies the fastest)
#          C order means that operating row-rise on the array will be slightly quicker
#          FORTRAN-contiguous order in memory (first index varies the fastest).
#          F order means that column-wise operations will be faster. 
#          ‘A’ means to read / write the elements in Fortran-like index order if,
#          array is Fortran contiguous in memory, C-like order otherwise
# ----------------------------------------------------------------------------------------------------------------------------------------
# Return : 
# Flattened array having same type as the Input array and and order as per choice.
# ----------------------------------------------------------------------------------------------------------------------------------------
# Code :
two_d_array = np.random.randint(1, 10, size=(3,3))  # 3D array
print(f"Main array {two_d_array.shape} : \n {two_d_array}\n") # array print
ravel_two_d_array = np.ravel(two_d_array)
print(f"After ravel {ravel_two_d_array.shape} : \n {ravel_two_d_array}") # array print

Main array (3, 3) : 
 [[7 2 5]
 [6 2 6]
 [7 9 6]]

After ravel (9,) : 
 [7 2 5 6 2 6 7 9 6]
