Array Ravel

In [1]:
import numpy as np

In [3]:
# ----------------------------------------------------------------------------------------------------------
# numpy.ndarray.flatten() function return a copy of the array collapsed into one dimension.
# ----------------------------------------------------------------------------------------------------------
# Syntax : numpy.ndarray.flatten(order=’C’)
# ----------------------------------------------------------------------------------------------------------
# Parameters :
# order : [{‘C’, ‘F’, ‘A’, ‘K’}, optional] ‘C’ means to flatten in row-major (C-style) order. 
# ‘F’ means to flatten in column-major (Fortran- style) order. 
# ‘A’ means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise. 
# ‘K’ means to flatten a in the order the elements occur in memory. The default is ‘C’.
# ----------------------------------------------------------------------------------------------------------
# Return : [ndarray] A copy of the input array, flattened to one dimension.
# ----------------------------------------------------------------------------------------------------------
# Code : 
two_d_array = np.random.randint(1, 10, size=(3,3))  # 3D array
print(f"Main array {two_d_array.shape} : \n {two_d_array}\n") # array print
flattened_two_d_array = two_d_array.flatten()
print(f"After flatten {flattened_two_d_array.shape} : \n {flattened_two_d_array}") # array print

Main array (3, 3) : 
 [[9 3 8]
 [4 8 7]
 [2 9 9]]

After flatten (9,) : 
 [9 3 8 4 8 7 2 9 9]
