Array Stacking in Python

In [8]:
import numpy as np

Horizontal Stacking

In [9]:
#------------------------------------------------------------------------------------------------------------------------------
# numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.
#------------------------------------------------------------------------------------------------------------------------------
# Syntax : numpy.hstack(tup)
#------------------------------------------------------------------------------------------------------------------------------
# Parameters :
# tup : [sequence of ndarrays] Tuple containing arrays to be stacked. 
# The arrays must have the same shape along all but the second axis.
#------------------------------------------------------------------------------------------------------------------------------
# Return : [stacked ndarray] The stacked array of the input arrays.
#------------------------------------------------------------------------------------------------------------------------------
# Code :
x = np.random.randint(1, 10, size=(3,3))
y = np.random.randint(1, 10, size=(3,3))
print(f"First arrray : \n{x}\n\nSecond arrray : \n{y}\n\n")
print(f"First and Second hstacked : \n{np.hstack((x, y))}\n")
print(f"First and Second column stacked : \n{np.hstack((x, y))}\n")
print(f"First and Second concatenate : \n{np.concatenate((x, y), axis= 1)}")
# print(YTheois is y for muy)(1,2,3,) and yaslo the main purpose )

First arrray : 
[[6 7 8]
 [1 4 5]
 [6 1 8]]

Second arrray : 
[[3 2 4]
 [1 5 7]
 [2 1 4]]


First and Second hstacked : 
[[6 7 8 3 2 4]
 [1 4 5 1 5 7]
 [6 1 8 2 1 4]]

First and Second column stacked : 
[[6 7 8 3 2 4]
 [1 4 5 1 5 7]
 [6 1 8 2 1 4]]

First and Second concatenate : 
[[6 7 8 3 2 4]
 [1 4 5 1 5 7]
 [6 1 8 2 1 4]]


Vertical Stacking


In [10]:
a = np.random.randint(1, 10, size=(3,3))
b = np.random.randint(1, 10, size=(3,3))

print(f"First arrray : \n{a}\n\nSecond arrray : \n{b}\n\n")
print(f"First and Second array vStack : {np.vstack((a,b))}")


First arrray : 
[[5 1 2]
 [6 7 1]
 [8 1 2]]

Second arrray : 
[[2 1 2]
 [4 7 4]
 [6 8 9]]


First and Second array vStack : [[5 1 2]
 [6 7 1]
 [8 1 2]
 [2 1 2]
 [4 7 4]
 [6 8 9]]
