Array Indexing

In [18]:
import numpy as np

In [19]:
one_d_array = np.array([1,2,3,4,5])  #1D array
print(one_d_array) # array print
print(f"1st element of 1D array is : {one_d_array[0]}")

[1 2 3 4 5]
1st element of 1D array is : 1


In [20]:
two_d_array = np.random.randint(1, 10, size=(2,2))  #1D array
print(two_d_array) # array print
print(f"1st element of 2D array is : {two_d_array[0][0]}")
print(f"2nd element of 2D array is : {two_d_array[0, 1]}")

[[9 2]
 [5 6]]
1st element of 2D array is : 9
2nd element of 2D array is : 2


In [21]:
three_d_array = np.random.randint(1, 10, size=(2,2,2))  #1D array
print(three_d_array) # array print
print(f"2nd element of 2nd position 3D array is : {three_d_array[1][0][1]}")

[[[8 3]
  [5 6]]

 [[8 1]
  [5 9]]]
2nd element of 2nd position 3D array is : 1
