Array Reshape

In [1]:
import numpy as np

In [9]:
# ----------------------------------------------------------------------------------------------
# The numpy.reshape() function shapes an array without changing the data of the array.
# ----------------------------------------------------------------------------------------------
# Syntax:
# numpy.reshape(array, shape, order = 'C')
# ----------------------------------------------------------------------------------------------
# Parameters : 
# array : [array_like]Input array
# shape : [int or tuples of int] e.g. if we are arranging an array with 10 elements then shaping
#         it like numpy.reshape(4, 8) is wrong; we can do numpy.reshape(2, 5) or (5, 2)
# order  : [C-contiguous, F-contiguous, A-contiguous; optional]         
#          C-contiguous order in memory(last index varies the fastest)
#          C order means that operating row-rise on the array will be slightly quicker
#          FORTRAN-contiguous order in memory (first index varies the fastest).
#          F order means that column-wise operations will be faster. 
#          ‘A’ means to read / write the elements in Fortran-like index order if,
#          array is Fortran contiguous in memory, C-like order otherwise
# ----------------------------------------------------------------------------------------------
# Return Type: 
# Array which is reshaped without changing the data.
# ----------------------------------------------------------------------------------------------
# Code : 
two_d_array = np.random.randint(1, 10, size=(2,3))  #1D array
print(f"Main array {two_d_array.shape} : \n {two_d_array}\n") # array print
reshaped_two_d_array = np.reshape(two_d_array, (3,2))
print(f"After reshape {reshaped_two_d_array.shape} : \n {two_d_array}") # array print

Main array (2, 3) : 
 [[7 8 3]
 [7 6 4]]

After reshape (3, 2) : 
 [[7 8 3]
 [7 6 4]]
