Array Resize

In [1]:
import numpy as np

In [5]:
# ----------------------------------------------------------------------------------------------------------------
# With the help of Numpy numpy.resize(), we can resize the size of an array. 
# Array can be of any shape but to resize it we just need the size i.e (2, 2), (2, 3) and many more. 
# During resizing numpy append repeate values of the array from first, if values at a particular place is missing.
# ----------------------------------------------------------------------------------------------------------------
# Parameters:
# new_shape : [tuple of ints, or n ints] Shape of resized array
# refcheck : [bool, optional] This parameter is used to check the reference counter. 
# By Default it is True.
# ----------------------------------------------------------------------------------------------------------------
# Returns: None
# ----------------------------------------------------------------------------------------------------------------
# Code : 
two_d_array = np.random.randint(1, 10, size=(2,3))  # 2D array
print(f"Main array {two_d_array.shape} : \n {two_d_array}\n") # array print
resized_two_d_array = np.resize(two_d_array, (3,3))
print(f"After reshape {resized_two_d_array.shape} : \n {resized_two_d_array}") # array print


Main array (2, 3) : 
 [[3 7 9]
 [5 9 8]]

After reshape (3, 3) : 
 [[3 7 9]
 [5 9 8]
 [3 7 9]]
