Differences between Flatten() and Ravel() Numpy Functions


In [1]:
import numpy as np

| Ravel | Flatten |
| --- | --- |
| Return only reference/view of the original array | Return copy of the original array |
| If you modify the array you would notice that the value of the original array also changes | If you modify any value of this array value of the original array is not affected |
| Ravel is faster than flatten() as it does not occupy any memory | Flatten() is comparatively slower than ravel() as it occupies memory |
| Ravel is a library-level function | Flatten is a method of an ndarray object. Let us check out the difference in this code |

In [6]:
arr = np.random.randint(1, 10, size=(3,3))
print(f"Main array : \n {arr}")
raveled_arr = np.ravel(arr)
print(f"Reveled array : \n {raveled_arr}")
raveled_arr[0] = 155
print(f"\n AFTER CHANGE VALUE\n \n Main array : \n {arr}\nReveled array : \n {raveled_arr}")

Main array : 
 [[7 6 6]
 [7 3 8]
 [8 3 7]]
Reveled array : 
 [7 6 6 7 3 8 8 3 7]

 AFTER CHANGE VALUE
 
 Main array : 
 [[155   6   6]
 [  7   3   8]
 [  8   3   7]]
Reveled array : 
 [155   6   6   7   3   8   8   3   7]


In [7]:
arr2 = np.random.randint(1, 10, size=(3,3))
print(f"Main array : \n {arr2}")
flattened_arr = arr2.flatten()
print(f"Flattened_arr array : \n {flattened_arr}")
flattened_arr[0] = 155
print(f"\n AFTER CHANGE VALUE\n \n Main array : \n {arr2}\nFlattened_arr array : \n {flattened_arr}")

Main array : 
 [[4 2 5]
 [7 5 8]
 [3 8 1]]
Flattened_arr array : 
 [4 2 5 7 5 8 3 8 1]

 AFTER CHANGE VALUE
 
 Main array : 
 [[4 2 5]
 [7 5 8]
 [3 8 1]]
Flattened_arr array : 
 [155   2   5   7   5   8   3   8   1]
