numpy.hstack() in Python

In [1]:
import numpy as np

In [13]:
#------------------------------------------------------------------------------------------------------------------------------
# numpy.hstack() function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.
#------------------------------------------------------------------------------------------------------------------------------
# Syntax : numpy.hstack(tup)
#------------------------------------------------------------------------------------------------------------------------------
# Parameters :
# tup : [sequence of ndarrays] Tuple containing arrays to be stacked. 
# The arrays must have the same shape along all but the second axis.
#------------------------------------------------------------------------------------------------------------------------------
# Return : [stacked ndarray] The stacked array of the input arrays.
#------------------------------------------------------------------------------------------------------------------------------
# Code :
x = np.random.randint(1, 10, size=(3,3))
y = np.random.randint(1, 10, size=(3,3))
print(f"First arrray : \n{x}\n\nSecond arrray : \n{y}\n\n")
print(f"First and Second hstacked : \n{np.hstack((x, y))}\n")
print(f"First and Second column stacked : \n{np.hstack((x, y))}")

First arrray : 
[[2 6 8]
 [2 7 5]
 [5 3 5]]

Second arrray : 
[[4 4 8]
 [7 6 2]
 [4 2 8]]


First and Second hstacked : 
[[2 6 8 4 4 8]
 [2 7 5 7 6 2]
 [5 3 5 4 2 8]]

First and Second column stacked : 
[[2 6 8 4 4 8]
 [2 7 5 7 6 2]
 [5 3 5 4 2 8]]
